### ISSUE TITLE
Tuple index out of range

### ISSUE THREAD

**Issue by cchaswell** [mindandbrain/halfpipe#12]
**What happened?**
In order to test if there was something weird on our Isilon server that caused the problems with the log file and locks, we tried to test with a working directory on our other server. I still ran the halfpipe image from the usual server, but the only thing that changed was that the working directory is on another server. 

**Is there an error message?**
Halfpipe finds the functionals and anatomicals with the path to the new server. Right after typing the task name I get an error that says "tuple index out of range." The 19 scans are all the exact same as previous tests. 

**What is the exact command that you used to run `Halfpipe`?**
singularity run --cleanenv --bind /:/ext Halfpipe_latest.sif --use-cluster

**Which settings did you use?**
Working directory is /mnt/BIAC/munin.dhe.duke.edu/Data/Morey/Lab/Duke. 
Halfpipe image is located: /mnt/BIAC/duhsnas-pri.dhe.duke.edu/morey_biac/Lab/pipeline

Does the halfpipe image need to be on the same server as the working directory? Googling the error message doesn't give very specific issues. 
[log (1).txt](https://github.com/mindandbrain/Halfpipe/files/5365707/log.1.txt)
[err (1).txt](https://github.com/mindandbrain/Halfpipe/files/5365708/err.1.txt)
<img width="372" alt="Screen Shot 2020-10-12 at 10 16 34 AM" src="https://user-images.githubusercontent.com/40609098/95757849-aa221780-0c75-11eb-8294-4a52fa5a3be0.png">

**Comment by HippocampusGirl** [comment]
Hi Courtney, 
thank you for the detailed report! 

As far as I can tell, what happened was that some of your functional images seem to be 3D. As a result, the code failed when trying to read the repetition time from them. 
I added an extra check so that this should not happen again. 

Maybe we should add a specific error/warning message when BOLD images have only one volume? @ilyaveer

**Comment by cchaswell** [comment]
I totally see what I did wrong. I mixed up the anatomical and functional files in the folders and managed to have the issue several tries. *Hides under desk.* 

I'll fix my folders and try again. We are trying on this server to see if it will change anything with the logs and locking.
