### ISSUE TITLE
Slice timing correction issues

### ISSUE THREAD

**Issue by cchaswell** [mindandbrain/halfpipe#13]
**What happened?**
I get an error when doing slice timing correction. I always get warnings that say "Unexpected nifti slice_duration of 58.823528 ms in header for file "/ext/mnt/BIAC/munin.dhe.duke.edu/Data/Morey/Lab/Duke/func/39523.nii.gz" for all the scans. I am wondering if there is an issue due to these scans having TR and other info in milliseconds instead of seconds. I have to manually change the TR in the interface to 2.0 instead of 2000 that halfpipe automatically read. From the crash.txt it seems like the slice timing info in the nifti is causing these crashes. 

**Is there an error message?**

(ignore the tuple index error that is still at the top of the file from earlier tries). 
[crash-20201012-161003-ch186-slice_timing_correction-8c3fc253-43a3-44f6-8acf-9c1280f667c3.txt](https://github.com/mindandbrain/Halfpipe/files/5368304/crash-20201012-161003-ch186-slice_timing_correction-8c3fc253-43a3-44f6-8acf-9c1280f667c3.txt)
[err.txt](https://github.com/mindandbrain/Halfpipe/files/5368305/err.txt)

**What is the exact command that you used to run `Halfpipe`?**

**Which settings did you use?**
This is what is in the crash file. I am assuming the slice timing was automatically read from the nifti and needs to be divided by 1000.

slice_encoding_direction = k
slice_timing = [58.82353125, 176.47059375, 294.11765625, 411.76471875, 529.41178125, 647.05884375, 764.70590625, 882.35296875, 1000.00003125, 1117.64709375, 1235.29415625, 1352.94121875, 1470.58828125, 1588.23534375, 1705.88240625, 1823.52946875, 1941.17653125, 0.0, 117.6470625, 235.294125, 352.9411875, 470.58825, 588.2353125, 705.882375, 823.5294375, 941.1765, 1058.8235625, 1176.470625, 1294.1176875, 1411.76475, 1529.4118125, 1647.058875, 1764.7059375, 1882.353]
tpattern = <undefined>
tr = 2.0s

**Comment by HippocampusGirl** [comment]
Dear Courtney,

Could you send me the spec.json file from your working directory and an example image file where the error occurred? 
I am only interested in the header data of the nii file, so you can remove any potentially sensitive image data e.g. by `fslmaths image.nii -mul 0 for_lea.nii`
