### ISSUE TITLE
Halfpipe user interface won't load

### ISSUE THREAD

**Issue by cchaswell** [mindandbrain/halfpipe#17]
**What happened?**
I have downloaded the beta 5 image, but when I run the command to get the Halfpipe user interface, nothing is happening. I have tried it on a couple different node on the cluster. I did try to delete the singularity/cache folder, as well, to see if that helped. I have also tried to re-run the version from last week that definitely worked for me and that will not open either. 

**Is there an error message?**
None, just won't load. 

**What is the exact command that you used to run `Halfpipe`?**
singularity run --cleanenv --bind /:/ext halfpipe_beta5.sif --use-cluster

**Which settings did you use?**
N/A but I did check to make sure my image forwarding was working on the cluster (able to open graphical interfaces). It's so bizarre because none of my halfpipe images will open, even previous ones that worked before. I have also messaged our cluster admin to ask if anything might cause the issue on our end. Let me know if you have any ideas.
<img width="388" alt="Screen Shot 2020-11-04 at 10 51 38 AM" src="https://user-images.githubusercontent.com/40609098/98138139-c853ef80-1e90-11eb-9ece-776dd44fe4e2.png">

**Comment by cchaswell** [comment]
I used the debug flag and it looks like an issue binding the mount point. Maybe this is something going on with my cluster and server, but I'm not sure exactly what. 
[ch186@blade25 pipeline2]$ singularity --debug run --cleanenv --bind /:/ext halfpipe_beta5.sif --use-cluster
DEBUG   [U=171602,P=17360] persistentPreRun()            Singularity version: 3.6.3+26-g75204a8
DEBUG   [U=171602,P=17360] persistentPreRun()            Parsing configuration file /usr/local/packages/singularity_v3.6.3/etc/singularity/singularity.conf
DEBUG   [U=171602,P=17360] handleConfDir()               /home/ch186/linux/.singularity already exists. Not creating.
DEBUG   [U=171602,P=17360] handleRemoteConf()            Ensuring file permission of 0600 on /home/ch186/linux/.singularity/remote.yaml
DEBUG   [U=171602,P=17360] getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=171602,P=17360] execStarter()                 Checking for encrypted system partition
DEBUG   [U=171602,P=17360] Init()                        Image format detection
DEBUG   [U=171602,P=17360] Init()                        Check for sandbox image format
DEBUG   [U=171602,P=17360] Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=171602,P=17360] Init()                        Check for sif image format
DEBUG   [U=171602,P=17360] Init()                        sif image format detected
DEBUG   [U=171602,P=17360] SetContainerEnv()             Forwarding TERM environment variable
VERBOSE [U=171602,P=17360] SetContainerEnv()             Setting HOME=/home/ch186/linux
VERBOSE [U=171602,P=17360] SetContainerEnv()             Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=171602,P=17360] init()                        Use starter binary /usr/local/packages/singularity_v3.6.3/libexec/singularity/bin/starter-suid
VERBOSE [U=0,P=17360]      print()                       Set messagelevel to: 5
VERBOSE [U=0,P=17360]      init()                        Starter initialization
DEBUG   [U=0,P=17360]      load_overlay_module()         Trying to load overlay kernel module
DEBUG   [U=0,P=17360]      load_overlay_module()         Overlay seems supported by the kernel
VERBOSE [U=0,P=17360]      is_suid()                     Check if we are running as setuid
VERBOSE [U=0,P=17360]      priv_drop()                   Drop root privileges
DEBUG   [U=171602,P=17360]  read_engine_config()          Read engine configuration
DEBUG   [U=171602,P=17360]  init()                        Wait completion of stage1
VERBOSE [U=171602,P=17370]  priv_drop()                   Drop root privileges permanently
DEBUG   [U=171602,P=17370]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=171602,P=17370]  init()                        Spawn stage 1
DEBUG   [U=171602,P=17370] startup()                     singularity runtime engine selected
VERBOSE [U=171602,P=17370] startup()                     Execute stage 1
DEBUG   [U=171602,P=17370] StageOne()                    Entering stage 1
DEBUG   [U=171602,P=17370] prepareAutofs()               Found "/proc/sys/fs/binfmt_misc" as autofs mount point
DEBUG   [U=171602,P=17370] prepareAutofs()               Could not keep file descriptor for user bind path /: no mount point
DEBUG   [U=171602,P=17370] prepareAutofs()               Could not keep file descriptor for bind path /etc/localtime: no mount point
DEBUG   [U=171602,P=17370] prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=171602,P=17370] prepareAutofs()               Could not keep file descriptor for bind path /mnt/BIAC: no mount point
^C

**Comment by HippocampusGirl** [comment]
Hi Courtney,

That's a lot of debug information, I'll try to see what I can find. 

I the meantime, could you try downloading and running another container to see if this is something specific to Halfpipe?
For example, you could try downloading and running the "lolcow" container, which is a container commonly used for testing, using `singularity build lolcow.simg docker://godlovedc/lolcow` and the running it as before.

**Comment by cchaswell** [comment]
Issue has been resolved. It was definitely on the end of our cluster system. The admin rebooted all the blades and it is loading the interface now. An update on the OS had been done previously.

So if anyone has this issue on their cluster, it is possibly that rebooting the blades will solve it.
