### ISSUE TITLE
Beta 5 Crash report resultdicts

### ISSUE THREAD

**Issue by cchaswell** [mindandbrain/halfpipe#19]
It looks like Beta 5 ran fine for me, but I did get a crash report for each subject labeled "resultsdicts." I am still sorting through all of the files to check outputs but thought you might like to see the crash logs for this error. I attached one crash file but I have one for each subject.
[crash-20201106-150423-ch186-make_resultdicts-c34bed6a-b1f3-466a-a08d-792cee643099.txt](https://github.com/mindandbrain/halfpipe/files/5503430/crash-20201106-150423-ch186-make_resultdicts-c34bed6a-b1f3-466a-a08d-792cee643099.txt)

Also, there are some weird files in the folder all ending with ~.EDU. I assume from the new logging/locking fix. 
 Are the safe to delete? 
<img width="921" alt="Screen Shot 2020-11-06 at 3 44 21 PM" src="https://user-images.githubusercontent.com/40609098/98413033-f7ac5d00-2046-11eb-9ec0-6252e65a3255.png">

Inside the file just says something like this with a number:
"/ext/mnt/munin/Morey/Lab/Dukerest/.log.txt.lock|blade14.dhe.duke.edu|11945|2478797660148851099"

**Comment by HippocampusGirl** [comment]
Dear Courtney, 

Sorry for the delay, but the issue should now be fixed. After some more testing, we should be sending around Beta 6 with the fix soon.
